# Generated by Django 3.1.7 on 2021-03-28 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_details',
            fields=[
                ('customer_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('mobile_number', models.IntegerField()),
                ('email_id', models.CharField(max_length=30)),
                ('Joined_date', models.DateField()),
                ('grand_total', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('cid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('edate', models.DateField()),
                ('amount', models.IntegerField()),
                ('super_coin_detail', models.IntegerField()),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.customer_details')),
            ],
        ),
        migrations.CreateModel(
            name='Offerproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('discount', models.IntegerField()),
                ('scoin', models.IntegerField()),
                ('edate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('offers', models.CharField(max_length=100)),
                ('offerid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('scoin', models.IntegerField()),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('edate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('edate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('created_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('brand_name', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='products')),
            ],
        ),
        migrations.CreateModel(
            name='purchase_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supercoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('scoin', models.IntegerField()),
                ('edate', models.DateField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customers')),
            ],
        ),
        migrations.CreateModel(
            name='purchased_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounted_price', models.IntegerField(blank=True, null=True)),
                ('Offerproduct_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.offerproduct')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer_details')),
                ('offer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.offers')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('scoin', models.IntegerField()),
                ('pname', models.CharField(max_length=30)),
                ('discount', models.IntegerField()),
                ('offerid', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customers')),
                ('offers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.offers')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.offerproduct')),
            ],
        ),
        migrations.AddField(
            model_name='offerproduct',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=30)),
                ('customer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.customer_details')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer_details')),
                ('Product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product_details')),
            ],
        ),
        migrations.CreateModel(
            name='available_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounted_price', models.IntegerField(blank=True, null=True)),
                ('Offerproduct_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.offerproduct')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer_details')),
                ('offer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.offers')),
            ],
        ),
    ]
