# Generated by Django 3.1.7 on 2021-03-28 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210328_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offers', models.CharField(max_length=100)),
                ('offerid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('scoin', models.IntegerField()),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('edate', models.DateField()),
                ('photo', models.ImageField(upload_to='offers')),
            ],
        ),
        migrations.CreateModel(
            name='Offerproducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField()),
                ('scoin', models.IntegerField()),
                ('edate', models.DateField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product_details')),
            ],
        ),
        migrations.AlterField(
            model_name='available_product',
            name='Offerproduct_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.offerproducts'),
        ),
        migrations.AlterField(
            model_name='available_product',
            name='offer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.offer'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='offers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.offer'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.offerproducts'),
        ),
        migrations.AlterField(
            model_name='purchased_product',
            name='Offerproduct_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.offerproducts'),
        ),
        migrations.AlterField(
            model_name='purchased_product',
            name='offer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.offer'),
        ),
        migrations.DeleteModel(
            name='Offerproduct',
        ),
        migrations.DeleteModel(
            name='Offers',
        ),
    ]
